### ISSUE TITLE
Node list without root string

### ISSUE THREAD

**Issue by TrademarkTM** [Sashie/skript-yaml#11]
In the previous version, I was able to use `yaml nodes "messages" from "yaml"` to get a node list and save it with the subnode name. However, `yaml node list` returns the root like `messages.something` which is not helpful at all.

If you're able to loop those nodes, you already have the root one, and can use `rootnode.%loop-value%` which is way more friendly to use.

If you can, please return back to the old node list, or add an option to get it without the root. It's way easier to add "rootnode." than to split and get the last value.
Thanks!

**Comment by Sashie** [comment]
Yeah i'll add a thing for that
