### ISSUE TITLE
Doesn't want a tab for indentation 

### ISSUE THREAD

**Issue by uiytt** [Sashie/skript-yaml#13]
I'm in 1.12 with skript dev 36 and i have skript-yaml in 1.2.4 
I have this code : 
```
on load:
	log "a"
	load yaml "plugins/test.yml" as "config"
	log "b"
```
i found this : `found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)`
But this is strange, in skript we must use tab for indentation, (if i put 4 spaces, i have an error) 
So why the addons is asking me to remove the tab ?

**Comment by AlexLew95** [comment]
what, where you "found" this? And no, you can use space. You can't mix spaces and tabs

**Comment by uiytt** [comment]
i found it when i reload this skript in my console 

next,  yes but i will not use space in my script instead of space, it's horrible :/

**Comment by AlexLew95** [comment]
Yeah, just don't load wrong yaml lol, end of the issue

**Comment by uiytt** [comment]
yes but can it be written somewhere that the error applies to yaml and not to the script?

**Comment by Sashie** [comment]
im pretty sure the whole error points to it being from skript-yaml if you just read through it, using spaces in yaml is not a limitation that i put there...

**Comment by uiytt** [comment]
Not at any moment there is writing that this error came from the YAML, can you just change that please ?

**Comment by Sashie** [comment]
that message that you are getting originate from this bit of code from within snakeyaml itself, im not able to change the message...
https://bitbucket.org/asomov/snakeyaml/src/e66e35cbbaf4354cc61c0199f5b06388201b7829/src/main/java/org/yaml/snakeyaml/scanner/ScannerImpl.java?at=default&fileviewer=file-view-default#ScannerImpl.java-416

**Comment by uiytt** [comment]
ok
