### ISSUE TITLE
Issue with condition of node/path existance

### ISSUE THREAD

**Issue by Simuciokas** [Sashie/skript-yaml#2]
https://hastebin.com/evucanefeg.sql
Works correctly (can reload many times with no errors), but if I change the 
`yaml "version" in "config" does not exist:`
 to 
`yaml node "version" in "config" does not exist:` 
I am greeted with an error on the console on the 2nd (and every other) reload of the script:
https://hastebin.com/nosuwufope.md

Step by step:
- check if Mobs folder doesn't exist if not, delete it
- load script with the **node** part in the condition
- reload the script

**Comment by Sashie** [comment]
Thanks for pointing that out, the 'node exists' condition and 'yaml' expression have conflicting syntax.
Maybe its fixed in the next version.

**Comment by Sashie** [comment]
im assuming this either works now or found a better way to do it, closing for now..
