### ISSUE TITLE
Can't use on Spigot 1.16.4

### ISSUE THREAD

**Issue by sparrowhe** [Sashie/skript-yaml#24]
Hello. I can't use this plugin on spigot 1.16.4 with skript 2.4.0. It can't creat new yaml file. Can u help me?

**Comment by sparrowhe** [comment]
![image](https://user-images.githubusercontent.com/26871028/104191099-043e9e80-5458-11eb-99fe-31dfb8330871.png)

**Comment by Olyno** [comment]
Do you have any error?

**Comment by sparrowhe** [comment]
fixed, not this plugin's error
