### ISSUE TITLE
I'm getting stuck

### ISSUE THREAD

**Issue by Bencz6811** [Sashie/skript-yaml#26]
Hi

I would like to create a script which is list the coordinates whick is in the **Kor.yml**.

I can't loop it through because he can't understand the line, but I try some other ways but it didn't work

My code:

`command /kors:
	trigger:
		loop yaml node keys "list" from "plugins/Config/Kor.yml":
			broadcast yaml value loop-node from loop-list
`

**Comment by wallace4BR** [comment]
you can use this as a workaround
```command /kors: 
	trigger:
		loop yaml node keys "list" from "plugins/Config/Kor.yml":
			broadcast yaml value "%loop-node%" from "%loop-id%"```

**Comment by Sashie** [comment]
> yaml value loop-node from loop-list

Incorrect use of the yaml expression
