### ISSUE TITLE
Will this plugin be upgraded to 1.17

### ISSUE THREAD

**Issue by NUTT1101** [Sashie/skript-yaml#28]
This is a very good plugin for skript.
Please upgrade to 1.17!!!

**Comment by LowScarlet** [comment]
dead

**Comment by Sashie** [comment]
Technically this plugin doesn't need to be updated to be used for 1.17 however there is a new skript version that requires that I update

**Comment by Sashie** [comment]
There is an unreleased version in my discord channel
