### ISSUE TITLE
Cant write EntityType to yaml

### ISSUE THREAD

**Issue by Lotzyprod** [Sashie/skript-yaml#30]
When I try to write org.bukkit.entity.EntityType in yaml an empty entry is created in the list, or an empty value in the entry
Like this:

entities:
-
-
entity: 

Code:
on rightclick:
  if clicked entity is set:
    load yaml "someyaml.yml" as "yaml"
    set yaml value "entity" from "yaml" to (clicked entity).getType()
    save yaml "yaml"
    unload "yaml"
    
 Purpur 1.16.5, Skript 2.5.3, latest Skript-yaml (the previous version had a similar problem), Skript-reflect 2.2.2
 And surprisingly, everything works fine with the %block%.getType()

**Comment by Sashie** [comment]
That method you are referencing is returning a bukkit entity itself

Assuming a pig, that skript expression leads to this class... https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/entity/PigData.java#L72

**Comment by Lotzyprod** [comment]
![image](https://user-images.githubusercontent.com/35628167/125555245-5a2f6f5e-a792-424b-94ed-adfdd36e4b60.png)
same result.
(clicked entity).getType() return a EntityType
I have also tried EntityType.valueOf("SOMEMOB") - some result , empty value/list

**Comment by Sashie** [comment]
Rip, ill have to explore deeper
