### ISSUE TITLE
Retrieving Value Bug(String with '__skriptclass__' not read properly)

### ISSUE THREAD

**Issue by EarthAgar** [Sashie/skript-yaml#31]
I've got a yml value set to a large json string and my issue is that when I try to grab the string from the yml file it always returns `<none>`. When using a file manager I can see that everything is set correctly.

**Steps to reproduce:**
    Use 1.16.5 Paper
    Install Skript-yaml 1.4 ([link](https://github.com/Sashie/skript-yaml/releases))
    Install Skript-json 1.1.1 ([link](https://github.com/btk5h/skript-json/releases))
    Install Skript 2.6-beta2 ([link](https://github.com/SkriptLang/Skript/releases))
    Install Runtime Skript Addon Patcher ([link](https://github.com/TPGamesNL/SkriptAddonPatcher/releases/tag/v1.0))
    Use the code from this paste: https://paste.helpch.at/uporuruvas.rb

**Comment by EarthAgar** [comment]
After further testing I've discovered a few things:

Using SkriptYAML 1.4 with 2.6beta-2 has the same issue
Using SkriptYAML 1.4 with 2.5.3 has the same issue
Using SkriptYAML 1.3.2 with 2.5.3 has the same issue

So it seems to be an issue across all versions of SkriptYML. I don't receive any console errors or skript errors either. I believe I've done all the testing I can so I'll have to leave it here for now and see if anyone else can find anything.

My guess is possibly the formatting of the string or maybe the size of the string causes it to not load.

**Comment by Sashie** [comment]
can you send the json string? 
also for any versions of Skript you can still use 1.4 ^.^
but thanks for testing that it works the same on old versions <3

**Comment by EarthAgar** [comment]
> can you please send the json string?
> also for any versions of Skript you can still use 1.4 ^.^
> but thanks for testing that it works the same on old versions <3

Here is the exact contents of the file when its created and values are set https://paste.helpch.at/ilajalagub.makefile

**Comment by Sashie** [comment]
Thanks I'll see what I find

**Comment by EarthAgar** [comment]
Oh neat, good job on finding the issue! Glad this was finally caught :)
