### ISSUE TITLE
getter of 'yaml value' is broken. 

### ISSUE THREAD

**Issue by Obliviated** [Sashie/skript-yaml#32]
**Debug Code:**
```	
load yaml "plugins/BlokRanks/config.yml" as "ranks_config"
set {_x} to (yaml value "sa" from "ranks_config")
broadcast "%{_x}%"
loop all yaml nodes of "ranks_config":
	broadcast "%loop-value%"
```

**Debug Result:**
![image](https://user-images.githubusercontent.com/36128276/129560117-63685459-c017-4189-a771-98bd0c4c6c06.png)

**Config:**
```
sa: 'as'
vip:
#...
```

**Versions:**
Server: 1.16.5 Paper-783 
Skript: 2.5.3
Skript-YAML: 1.4
Java: JDK 16

**Errors:**
No errors in the console.
No errors about skript parse.
No errors during initalize of skript and skript-yaml.

[Click to see full config.yml](https://pastebin.ubuntu.com/p/2TVJRzgZxz/)

**Comment by Sashie** [comment]
I tested with the same specs you gave and it works for me so I'll try to have a few other people test it as well

![image](https://user-images.githubusercontent.com/17128178/129771950-8d17ab47-b294-49ef-9d3e-77a07b7c7497.png)

**Comment by Obliviated** [comment]
> I tested with the same specs you gave and it works for me so I'll try to have a few other people test it as well
> 
> ![image](https://user-images.githubusercontent.com/17128178/129771950-8d17ab47-b294-49ef-9d3e-77a07b7c7497.png)

Thank you for your interest. Can i help you for anything?

**Comment by Sashie** [comment]
I was unable to reproduce this issue
