### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by DevonPalma** [Sashie/skript-yaml#4]
Attempting to use code:
```
command /test:
	trigger:
		message "%all of the currently loaded yaml files%"
		load yaml "plugins/test/test.yml" as "test"
```
however in console receive error

> 07.04 19:34:22 [Server] WARN Plugin Skript v2.2-dev34 generated an exception while executing task 101
> 07.04 19:34:22 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: 0
> 07.04 19:34:22 [Server] INFO at sun.nio.fs.UnixPath.normalize(UnixPath.java:508) ~[?:1.8.0_05]
> 07.04 19:34:22 [Server] INFO at me.sashie.skriptyaml.skript.EffLoadYaml.execute(EffLoadYaml.java:81) ~[?:?]
> 07.04 19:34:22 [Server] INFO at me.sashie.skriptyaml.AsyncEffectOld.access$0(AsyncEffectOld.java:1) ~[?:?]
> 07.04 19:34:22 [Server] INFO at me.sashie.skriptyaml.AsyncEffectOld$1.run(AsyncEffectOld.java:36) ~[?:?]
> 07.04 19:34:22 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
> 07.04 19:34:22 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-93e20b3-31d3159]
> 07.04 19:34:22 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_05]
> 07.04 19:34:22 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_05]
> 07.04 19:34:22 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_05]

**Comment by DevonPalma** [comment]
Well, I was unable to update java, but I played a tiny bit with your code and got it to work to my needs

**Comment by Sashie** [comment]
what code did you end up using? I may as well add it in here so this doesn't bother anyone again

**Comment by Sashie** [comment]
I'm closing this issue since it's a java version related problem not mine per se
