### ISSUE TITLE
Error starting server - 1.20

### ISSUE THREAD

**Issue by Craafter** [Sashie/skript-yaml#49]
Greetings! I installed script-yaml on the server, but as soon as it is enabled it is consequently disabled, followed by an error (attached in .txt file)
**Software server**: PaperMC - 1.20
[error_plugin.txt](https://github.com/Sashie/skript-yaml/files/11848336/error_plugin.txt)

**Comment by TobyMinceraft** [comment]
I am also getting the same error.

**Comment by MennoGamed** [comment]
Same problem here! 
![afbeelding](https://github.com/Sashie/skript-yaml/assets/64696706/44961963-d345-4273-8d7c-49e511fd9ceb)

**Comment by TobyMinceraft** [comment]
UPDATE: See issue #46 
ShaneBee posted an update for 1.20
