### ISSUE TITLE
Add item data and meta data to skript serializer

### ISSUE THREAD

**Issue by khlfkk** [Sashie/skript-yaml#5]
if it is work we can edit the item via a yml file . thanks @Sashie 

(Add Items to serializer)

**Comment by khlfkk** [comment]
Thanks for Sashie:) i knew there are some feature will be added, if possible hope that add itemstack to yml function will be release first since it is very useful.

**Comment by Sashie** [comment]
I just have to test it and will release soon!

**Comment by Sashie** [comment]
Added in v1.2.1 <3
