### ISSUE TITLE
Loop yaml doesn't work in the latest version

### ISSUE THREAD

**Issue by uiytt** [Sashie/skript-yaml#8]
Skript: dev 34
Minecraft : 1.10.2
Skript-yaml : 1.2.4

When i use  : 
`loop yaml nodes "test" of "ID":`
It does not work
but 
`set {_test} to (yaml value "version" of "ID)`
is working

**Comment by Sashie** [comment]
the syntax for nodes in the yaml expression changed a few updates ago

**Comment by uiytt** [comment]
Ok so some exemple in the README are note updated...
like : https://github.com/Sashie/skript-yaml#effect-load-all-yaml-from-directory

And i'm not sure but according to [THIS](https://github.com/Sashie/skript-yaml#expression-yaml)
this should work : 
set {_test::*} to yaml node list "test1.test2" from "config"
But it doesn't work :/

**Comment by AlexLew95** [comment]
```vb
[[skript-]y[a]ml] (1¦value|2¦(node|path) list|3¦(node|path)[s with] keys|4¦list) %string% (of|in|from) %string% [without string checks]
```
It's
```vb
skript-yaml node list %string% from %string%
```
and which is
```vb
skript-yaml node list "Your_beautiful_node.YourValueForExample" from "plugins/YourFolder/YourFile.yml"
```
and which will return something like ``Your_beautiful_node`` in my example.
It's just knowing how to read a syntax you know...

**Comment by uiytt** [comment]
`set {_test::*] to skript-yaml node list "Your_beautiful_node.YourValueForExample" from "plugins/YourFolder/YourFile.yml"`
is exactly the same as : (with diferent name for the file and the path)  
`set {_test::*} to yaml node list "test1.test2" from "config"`

**Comment by AlexLew95** [comment]
Node list returns only 1 data, not more, so I don't know why you use list variable and not a simple variable.
